### PR TITLE
Compress VCFs with bgzip and index them with tabix

### LINKED ISSUE #391: Index output VCFs with tabix
We should tabix-index the VCFs that the pipeline creates.

For that, we need to compress the output VCFs with `bgzip` instead of regular `gzip`. That also means unfortunately that we cannot use `pigz` in the ConcatVCF step anymore. Possibly use https://github.com/nh13/pbgzip instead.

### PR DESCRIPTION
**Pull request by marcelm**
Closes #391

### CODE REVIEW

**Comment by marcelm** [comment]
Not sure if this even works. I couldn’t run the tests locally, so I’ll wait for Travis.

**Comment by MaxUlysse** [comment]
I'm pretty sure it won't work, but it's a good base.
I'd like to do that for all VCFs, but you don't need that.
I'll update the container for concatVCF, so the PR will work, and then I'll work from that ;-)
Thanks

**Comment by MaxUlysse** [comment]
In fact, you should be able to make them run by switching the container for the concatVCF process.
Specify the htslib container instead, and it should work fine.
Sorry that I didn't notice that earlier...

**Comment by marcelm** [comment]
The `docker.config` and `singularity.config` files do not mention `htslib`. There’s a `samtools` container, did you mean that one? Does that also contain htslib?

**Comment by marcelm** [comment]
Ah, although it’s not used in the current configuration, you provide a `maxulysse/htslib` container. I’ve changed it now.

**Comment by MaxUlysse** [comment]
It is actually used in the builReferences.nf script.
I can see that we got more tests succeed, so that's better.
I'll check what is still failing and see how to fix it.
Thanks

**Comment by MaxUlysse** [comment]
Ok, so no don't worry about the failed tests, the test is just trying to remove the old concatVCF container instead of removing the htslib container.
(We do need the space for the vep/snpeff containers that are huge)
I'll try to find a better way to rm old containers.

**Comment by marcelm** [comment]
Hi, I’ve switched to the htslib container and the tests pass now.

**Pull request merged**
