### PR TITLE
fix Variant Callers issue with changes for gender handling

### PR DESCRIPTION
**Pull request by MaxUlysse**
Hot fixes for Variant Callers induces by latest changes on PR #316

will be merged ASAP

### CODE REVIEW

**Comment by MaxUlysse** [comment]
`.choice(bamsTumor, bamsNormal) {it[2] == 0 ? 1 : 0}` it should have been `it[1]`
`idPatientNormal, idSampleNormal, bamNormal, baiNormal, idPatientTumor, genderTumor, idSampleTumor, bamTumor, baiTumor -> ` genderTumor should have been removed.

I managed to remove this 2 lines:
```
bamsNormalTemp = bamsNormalTemp.map { idPatient, idSample, bam, bai -> [idPatient, 0, idSample, bam, bai] }
bamsTumorTemp = bamsTumorTemp.map { idPatient, idSample, bam, bai -> [idPatient, 1, idSample, bam, bai] }
```
By moving the preparation for Ascat up a few lines.

**Comment by MaxUlysse** [comment]
Problem with VEP, I'm trying to fix that...

**Comment by marcelm** [comment]
Sorry and thanks!

**Comment by MaxUlysse** [comment]
No problems ;-)

**Comment by MaxUlysse** [comment]
I removed VEP from the tests at the moment.
There is something fishy here.
But we do need this fix on the Variant Calling

**Comment by marcelm** [comment]
I’m taking the liberty of merging this now because I need it to continue working. I hope that’s fine.

**Pull request merged**
