### PR TITLE
Skip RecalibrateBam step in more situations; make skippreprocessing work

### PR DESCRIPTION
**Pull request by marcelm**
Only a defined list of tools triggers the recalibrated BAM to be created.
Previously, we would check only whether HaplotypeCaller is the only tool
being run, but that is too restrictive. Now, the RecalibrateBam step is
also omitted with --tools=HaplotypeCaller,MultiQC, for example.

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Interesting.
I like this idea

**Comment by marcelm** [comment]
One change in behavior, see also what the tests do: If you do not specify any `--tools` that actually require a recalibrated BAM, then no recalibrated BAM is generated, for example with `--step=recalibrate --tools=MultiQC`

**Comment by MaxUlysse** [comment]
Is it OK to merge?

**Comment by marcelm** [comment]
Yes! ... if you are aware of my previous comment that `--step=recalibrate` without anything else will no longer generate a recalibrated BAM.

**Comment by MaxUlysse** [comment]
ok, so maybe think about that in #356 and rename recalibrate also ?

**Comment by marcelm** [comment]
I think the name is still fine: If `--tools=` is used with any of FreeBayes, MuTect1, MuTect2, etc., then the recalibrated BAM is still generated. And even with `--tools=HaplotypeCaller`, the recalibration is still done, it’s just that the BAM is not generated.

**Pull request merged**
