### PR TITLE
removed quotation marks from all parameter defitions that should be i…

### PR DESCRIPTION
**Pull request by malinlarsson**
…nterpreted as integers in multiplication with task.attempt

### CODE REVIEW

**Comment by malinlarsson** [comment]
fix #138

**Comment by malinlarsson** [comment]
Note - this only fixed the bug for running CAW on Milou using slurm. We still need to fix it for the other cases.

**Comment by MaxUlysse** [comment]
What were the other cases ?

**Comment by malinlarsson** [comment]
We need to fix it in amanita.config, irma.config and milou-local.config

**Comment by szilvajuhos** [comment]
We can merge, re-configuring amanita is a bigger chunk of work.

**Pull request merged**
