### PR TITLE
Config clean

### LINKED ISSUE #246: Get rid of standard.config
... by merging it into `nextflow.config` since it is included in all profiles. @MaxUlysse volunteered :-)

### PR DESCRIPTION
**Pull request by MaxUlysse**
closes #246

### CODE REVIEW

**Comment by marcelm** [comment]
I did not test, but it looks good to me!

**Comment by MaxUlysse** [comment]
[works badge](https://github.com/nikku/works-on-my-machine)

**Comment by marcelm** [comment]
Great link :-)

**Comment by MaxUlysse** [comment]
I'm also a big fan of the Volkswagen approach: https://github.com/auchenberg/volkswagen

**Pull request merged**
