### PR TITLE
Simplify logic in multiple places

### PR DESCRIPTION
**Pull request by marcelm**
In particular, do not use `assert` when an `if` suffices.

Also changed this construct
```
a = condition ? value : a
```
to
```
if (condition) {
  a = value
}
```
because I find it suprising that it ends up self-assigning `a` to `a` when the condition is false.

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Yes, but groovy logic use that a lot, that's why I put it almost everywhere ;-)

**Comment by marcelm** [comment]
Do you mean that it’s done that way in example `main.nf` files?

**Comment by MaxUlysse** [comment]
I'll verify it tomorrow

**Comment by MaxUlysse** [comment]
Looking at the nf scripts from the CRG lab (https://github.com/cbcrg), they mainly use the ? : instead of the classical if then else.
I don't mind using either, but I guess it could be a decision to made as a coding best practices for nf workflow.
Shall we talk about that with other nf coders here at SciLife Lab?

**Comment by marcelm** [comment]
I don’t have a problem with using the ternary operator; it is very convenient. What I do not think is good style is to use it to re-assign the same value as I wrote in my first comment above:
```
a = condition ? value : a
```
If it were
```
a = condition ? value1 : value2
```
it would be fine. But re-assigning a to itself hides what is going on.

**Comment by MaxUlysse** [comment]
Oh I see.
Sorry, I totally misunderstood...
I believed you wanted to remove all ternary if, not just the malformed ones...
I totally agree then...

**Comment by MaxUlysse** [comment]
Is this ok if we do that?
```
a = condition1 ? value1 :
    condition2 ? value2 :
    condition3 ? value3 :
                 empty
```

**Comment by marcelm** [comment]
No.

**Pull request merged**
