### PR TITLE
configuration for testing on a small desktop machine without docker

### PR DESCRIPTION
**Pull request by szilvajuhos**

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Why would you want to go into the trouble of installing all tools and the module system on a small desktop machine ?

**Comment by szilvajuhos** [comment]
Exactly. My actual problem is that docker screws up my network interface and other stuff on my laptop. So, instead of fixing the Mint distribution I can do something that I am familiar with.  
OTOH I do agree the way forward is to have docker/singularity/whatever. If you think it is lame, I can keep it on my fork only, not merging into upstream.

**Comment by MaxUlysse** [comment]
Do you have the same problem with Singularity ?

But I don't really see a problem into having that in the master branch.
If it's too much we'll get rid of it the next time we do a big clean up.

**Comment by MaxUlysse** [comment]
If #413 fixes your problem, then we can forget about this PR, otherwise, we can merge both of them.

**Comment by szilvajuhos** [comment]
OK, looks it can be done with singularity

**Pull request closed without merging**
