### PR TITLE
Unify milou and bianca configurations

### LINKED ISSUE #215: Unify bianca and milou configuration
This is the current diff between `configuration/milou.config` and `configuration/bianca.config`:
```
--- bianca.config       2017-03-20 16:18:49.656447658 +0100
+++ milou.config        2017-03-20 16:18:49.721844364 +0100
@@ -117,7 +117,7 @@
     memory = {params.singleCPUMem * 2 * task.attempt}
   }
   $RunAscat {
-    module = ['R/3.3.2']
+    module = ['R/3.2.3']
     cpus = 1
     memory = {params.singleCPUMem * 2 * task.attempt}
   }
```
Is this worth keeping two separate files?

### PR DESCRIPTION
**Pull request by marcelm**
This merges both configurations into a single `uppmax` one. `-profile bianca` is no longer supported, use `-profile standard` or leave out the option entirely.

Closes #215

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Shall we make it into -profile uppmax ?

**Comment by marcelm** [comment]
The `standard` profile is by convention the default one that Nextflow runs when you do not use `-profile`, so if we turn this into `-profile uppmax`, we need to rename one of the other profiles to `standard`.

**Comment by MaxUlysse** [comment]
Makes sense

**Comment by szilvajuhos** [comment]
OK for me, the less extra profiles the better

**Pull request merged**
