### PR TITLE
Rename steps

### LINKED ISSUE #356: Rename steps
As discussed on Slack, we could rename two of the steps:

* `skippreprocessing` → `variantcalling`
* `preprocessing` → `mapping`

The semantics should also be made a bit clearer: The `--step` gives the step at which the pipeline *starts*.

### PR DESCRIPTION
**Pull request by MaxUlysse**
closes #356

### CODE REVIEW

**Comment by MaxUlysse** [comment]
It's ready to merge, but I do think it would be good to merge this PR when merging #385 and closing #380

**Comment by marcelm** [comment]
Could you make this change in a backwards-compatible way?
Perhaps like this:
```
step = params.step.toLowerCase()
if (step == 'preprocessing') step = 'mapping'
if (step == 'skippreprocessing') step = 'variantcalling'
```
Then you could merge it already now without breaking anything.

**Comment by MaxUlysse** [comment]
I totally can, but I'm waiting on this PR for an update of Nextflow from Uppmax, then we'll ditch the modules and work with containers, so it'll be a huge change, so I'm guessing a change of name for the steps at the same time would be a good occasion (and I can forget the retro-compatibility).

**Comment by MaxUlysse** [comment]
You were completely right.
Sorry that I didn't realize that earlier.
I should have done that from the beginning and not have this PR rusting here all that time...

**Comment by szilvajuhos** [comment]
Indeed it has to be backward-compatible: changing the name confuses users.

**Comment by MaxUlysse** [comment]
It is now backward-compatible.
So you can merge it

**Pull request merged**
